{
  "os": "linux",
  "dist": "trusty",
  "sudo": "required",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "before_cache": [
    "rm -rf node_modules/.cache"
  ],
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "google-chrome"
      ],
      "packages": [
        "google-chrome-stable"
      ]
    }
  },
  "script": [
    "npm run build"
  ],
  "install": [
    "npm install"
  ],
  "node_js": ["8", "10"],
  "language": "node_js"
}
